# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

# Added manually by Will Landau

branches:
  except:
  - gh-pages
  - scheduler-spec

warnings_are_errors: true

r_packages:
  - covr
  - lintr

# From Jim Hester, for avoiding timeouts
script:
  - |
    R CMD build .
    travis_wait 20 R CMD check drake*tar.gz --no-tests
    travis_wait 20 Rscript -e 'covr::codecov()'

after_success:
  - Rscript -e 'lintr::lint_package()'

after_failure:
  - find *Rcheck -name '*fail' -print -exec cat '{}' \;
