# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
repos:
  CRAN: https://cloud.r-project.org

bioc_packages:
  - graph

# Added manually by Will Landau
branches:
  except:
  - gh-pages

warnings_are_errors: true

addons:
  apt:
    packages:
      - libudunits2-dev
      - libzmq3-dev

r_packages:
  - clustermq
  - downloader
  - forcats
  - ggplot2
  - lintr
  - pkgdown
  - readxl

r_github_packages:
  - r-lib/covr

before_script:
  - chmod +x ./pkgdown.sh

# From Jim Hester, for avoiding timeouts
script:
  - |
    R CMD build .
    R CMD INSTALL drake*tar.gz
    Rscript pkgdown.R
    travis_wait 20 R CMD check drake*tar.gz --no-tests
    travis_wait 20 Rscript -e 'cov <- covr::package_coverage()' -e 'print(cov)' -e 'covr::codecov(coverage = cov)'

after_success:
  - ./pkgdown.sh
  - Rscript -e 'lintr::lint_package()'

after_failure:
  - find *Rcheck -name '*fail' -print -exec cat '{}' \;

env:
  - NOT_CRAN = true
