# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

# Added manually by Will Landau
branches:
  except:
  - gh-pages

warnings_are_errors: true

addons:
  apt:
    packages:
      - libudunits2-dev
      - libzmq3-dev

r_packages:
  - BiocManager
  - clustermq
  - covr
  - downloader
  - forcats
  - ggplot2
  - lintr
  - pkgdown
  - readxl

before_script:
  - chmod +x ./pkgdown.sh
  - Rscript -e 'BiocManager::install("CodeDepends", update = FALSE, ask = FALSE)'

# From Jim Hester, for avoiding timeouts
script:
  - |
    R CMD build .
    R CMD INSTALL drake*tar.gz
    Rscript -e 'devtools::test()'
    travis_wait 20 R CMD check drake*tar.gz
    travis_wait 20 Rscript -e 'cov <- covr::package_coverage()' -e 'print(cov)' -e 'covr::codecov(coverage = cov)'

after_success:
  - Rscript -e 'lintr::lint_package()'
  - Rscript pkgdown.R
  - ./pkgdown.sh

after_failure:
  - find *Rcheck -name '*fail' -print -exec cat '{}' \;

env:
  - NOT_CRAN=true
