# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest https://raw.githubusercontent.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  - ps: Bootstrap

# Adapt as necessary starting from here

branches:
  except:
  - gh-pages
  - scheduler

build_script:
  - travis-tool.sh install_deps
  - travis-tool.sh install_github ropensci/drake

test_script:
  - travis-tool.sh run_tests

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits

environment:
  NOT_CRAN: true
  _R_CHECK_FORCE_SUGGESTS_: false
  global:
    PKGTYPE: binary
    R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
    USE_RTOOLS: true
    WARNINGS_ARE_ERRORS: 1

  matrix:
    - R_VERSION: release
      arch: x64
